# Generated by Django 4.1.7 on 2023-04-06 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_quesmodel_ans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quesmodel',
            name='ans',
        ),
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.CharField(max_length=10)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.quesmodel')),
            ],
        ),
    ]
